name: Essentials
main: net.ess3.Essentials
version: 2.9
website: http://tiny.cc/EssentialsWiki
description: Compatibility plugin for older plugins
authors: [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits]
depend: [Essentials-3]
