# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: EssentialsSigns
main: com.earth2me.essentials.signs.EssentialsSignsPlugin
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${build.number}
website: http://tiny.cc/EssentialsWiki
description: Provides signs, utilizing Essentials.
authors: [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits]
depend: [Essentials-3]